/*

    OpenGL loader generated by glad 0.1.33 on Mon Jul 20 16:13:42 2020.

    Language/Generator: D
    Specification: gl
    APIs: gl=3.3
    Profile: core
    Extensions:
        
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: False

    Commandline:
        --profile="core" --api="gl=3.3" --generator="d" --spec="gl" --extensions=""
    Online:
        https://glad.dav1d.de/#profile=core&language=d&specification=gl&loader=on&api=gl%3D3.3
*/

module glad.gl.all;


public import glad.gl.funcs;
public import glad.gl.ext;
public import glad.gl.enums;
public import glad.gl.types;
